### ISSUE TITLE
[Feature Request] Merge from command line

### ISSUE THREAD

**Issue by erichard** [emlynwest/changelog#25]
I would like to be able to merge two or more files directly from the command line. 

What do you think about such a feature ? Would you merge a PR ?

**Comment by emlynwest** [comment]
I don't see an issue with that, I'd be curious to see what you have 😄

**Comment by erichard** [comment]
I have something functional but it is all hardcoded. I am trying to use the config now.

**Comment by erichard** [comment]
@emlynwest Can you build a phar for the 1.3.0 release ?

**Comment by emlynwest** [comment]
I'm trying but the script in the repo is not building the phar correctly and I've no idea why at this time.

**Comment by emlynwest** [comment]
`./vendor/bin/robo create:phar` should build it. For some reason on my machine it's building a mostly empty phar, only the stub is getting added and everything else is missing, resulting in an invalid phar.
